### ISSUE TITLE
hide debug messages

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#1]
I hope you will consider to add a debug toggle in config.

debug: true

![image](https://user-images.githubusercontent.com/6004542/54966315-42e52b00-4f4a-11e9-86e8-89f9e86814a7.png)

**Comment by insanj** [comment]
@madtomic Will do!

**Comment by insanj** [comment]
Fix confirmed in release https://github.com/insanj/CommandPlates/releases/tag/0.3.3.2
