### ISSUE TITLE
bug: detections

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#10]
The commands are fired once but the checks is still checking after every second for gold and iron plates.
This is an improvement.

![image](https://user-images.githubusercontent.com/6004542/55366380-7a0d8c00-54b6-11e9-9c08-3b59ec3b704d.png)

**Comment by insanj** [comment]
Well that's just how Gold and Iron plates work. If you want me to disable the log, I can do so!

**Comment by insanj** [comment]
@madtomic Removed the detection log in this build, will test more and let you know if it's ready for Bukkit prime time tomorrow:

https://github.com/insanj/CommandPlates/releases/tag/0.3.5.1

**Comment by madtomic** [comment]
Will this remove the debug feature that you added a debug: false/true in config?

**Comment by insanj** [comment]
Revisited in https://github.com/insanj/CommandPlates/releases/tag/1.0.0-pre1
