### ISSUE TITLE
a bit too much info

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#11]
This comes up when using reload command as a regular player.

I think, the best practice is to remove any reference to anything if you don't have enough permissions.

When they don't see it, they won't try to hack around it.

![image](https://user-images.githubusercontent.com/6004542/55366437-c658cc00-54b6-11e9-9df6-7c89a2e419b9.png)

**Comment by insanj** [comment]
Sounds good, will do 👍

**Comment by insanj** [comment]
@madtomic Will test tomorrow, but have code ready here in this pre-release if you wanna give it a shot first:

https://github.com/insanj/CommandPlates/releases/tag/0.3.5.1

**Comment by insanj** [comment]
Revisited in https://github.com/insanj/CommandPlates/releases/tag/1.0.0-pre1
