### ISSUE TITLE
change: revert the change

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#12]
> Well that's just how Gold and Iron plates work. If you want me to disable the log, I can do so!
_Originally posted by @insanj in https://github.com/insanj/CommandPlates/issues/10#issuecomment-479336864_

You can revert this change and I can just use the debug: true/false in config to toggle this.

With this commit, it removes the debugs.

Sorry about this change.

**Comment by insanj** [comment]
Sorry about delay, will be able to tackle this soon

**Comment by insanj** [comment]
Testing and building 1.0 with this change today: https://github.com/insanj/CommandPlates/releases/tag/1.0.0-pre1
