### ISSUE TITLE
improvement: clean up noperm messages

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#13]
You can remove all of the noperm messages to keep the plugin clean. This plugin was meant to be use by admins only. I will let you work out how to best present this. For other server owners, they might want to let players use this. So, these noperm messages might be needed in that case.

create
info
remove
reload

As for this one. It should not list at all for regular players.
list

![image](https://user-images.githubusercontent.com/6004542/55519942-026f6680-5648-11e9-8995-35715128d464.png)

![image](https://user-images.githubusercontent.com/6004542/55520093-b83ab500-5648-11e9-9b14-eb44c0597071.png)

**Comment by insanj** [comment]
Okay, can tweak these things and post a build in the next day or two

**Comment by insanj** [comment]
Included this in today's 1.0 testing build https://github.com/insanj/CommandPlates/releases/tag/1.0.0-pre1
