### ISSUE TITLE
/pplates remove platename

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#2]
I think, we should add a command to let admins to remove plates as well. 
Another way to remove it is to simple break the pressure plates itself. I think, this maybe the fastest way to remove it.

 command: pplates remove platename

**Comment by insanj** [comment]
@madtomic Good idea. Will do ASAP

**Comment by insanj** [comment]
Added in release https://github.com/insanj/CommandPlates/releases/tag/0.3.3.2
