### ISSUE TITLE
Bug: two separate commandplates in same location

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#3]
As you can see in this screen. If two commandplates are set at same location.
I am expecting both Example and ExampleConsole to be executed. It turns out the last one created will executed. I think, we should avoid having this bug by checking if the location already has a commandplates set up.

We can add a warning message. &cYou cannot create a commandplates here.

![image](https://user-images.githubusercontent.com/6004542/54966713-8db37280-4f4b-11e9-8692-8817fa7549e9.png)

**Comment by madtomic** [comment]
In case you are wondering, The wooden pressure plate is in question. The 2nd set of say message is from the stone pressure plate.

**Comment by insanj** [comment]
@madtomic Okay, will add a warning message and prevent a new one from being created until you delete the old one!

**Comment by insanj** [comment]
Added in release https://github.com/insanj/CommandPlates/releases/tag/0.3.4
