### ISSUE TITLE
Bug: wrong permissions

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#4]
I think you meant to use this.
    pplates.admin
    pplates.use
    pplates.<plate_name>

Release notes - BUG
0.3.2
@insanj insanj released this 4 days ago · 3 commits to master since this release
    Improve permission check on user who attempts to activate pressure plate, prioritizing:
    Operator
    pplate.admin
    pplate.use
    pplate.<plate_name>

**Comment by insanj** [comment]
@madtomic The correct permissions are `pplates`, that is true.
