### ISSUE TITLE
improvement: console commands permissions

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#5]
when executing console commands, it should execute as if the player had the permission for all the console commands for that plate.

Now, it just sends default no permission message.

![image](https://user-images.githubusercontent.com/6004542/54969160-8b551680-4f53-11e9-9d25-9dcf4685b785.png)

**Comment by insanj** [comment]
Weird, could you tell me what command you're trying to execute? If the `true` flag is set, it should use the console as the sender without any reference to the user.

**Comment by madtomic** [comment]
Normal players trying to use a plate with true flag is set. They have access with platename perm and get this error. Also try with use perm and have same issue.

**Comment by insanj** [comment]
Will keep trying to reproduce this. Not sure how the issue is occurring since clearly the commands are being sent, but instead of as the "console", they are being sent as someone else. I am not sure how that could happen.

**Comment by insanj** [comment]
@madtomic After many attempts, I am still unable to reproduce this issue. Could you perhaps make a video of the process from start to finish?

**Comment by madtomic** [comment]
It seems to be a random flu, I haven't been able to recreate this bug in 0.3.4. Close for now. Thanks for patching all the other issues.

**Comment by madtomic** [comment]
I was able to find the cause of this issue. It came from permission plugin itself. It was checking to see if the player has perm to use perm commands that I was using for testing.
