### ISSUE TITLE
improvement: command reload for config

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#7]
Add a reload command for config.

/pplates reload

I just thought of this would be a much faster way edit stuff using the config and reload.

**Comment by insanj** [comment]
👍 Good call, can add this shortly

**Comment by insanj** [comment]
@madtomic Haven't had a chance to test, but made a simple reload build here (will finish testing tomorrow):

https://github.com/insanj/CommandPlates/releases/tag/0.3.4.1
