### ISSUE TITLE
Bug: some plates are still spamming

### ISSUE THREAD

**Issue by madtomic** [insanj/CommandPlates#8]
gold_plate and iron_plate
Only these two pressure plate types are still affected by spamming.

The stone_plate and wood_plate doesn't spam and only run once the commands.

![image](https://user-images.githubusercontent.com/6004542/55301206-5cceb400-5409-11e9-88d2-19cd925bb71b.png)

**Comment by insanj** [comment]
@madtomic Based on those logs, it appears the plate is only activating once per second. What would you prefer?

**Comment by insanj** [comment]
Or is the issue that if you activate one plate and _stay_ standing on it, it activates again a second later? I'm unsure the specific bug here.

**Comment by madtomic** [comment]
This is standing on it. It should only fire once by default per use.
and the bug is it activated again a second later.

**Comment by insanj** [comment]
Ahh, okay, I'll try to fix this tomorrow. It must be because I've only tested with wooden and stone plates! Perhaps they are firing because of the different sensitivities. Good catch 👌

**Comment by insanj** [comment]
@madtomic Tested and confirmed working for me! Let me know how it goes for you: https://github.com/insanj/CommandPlates/releases/tag/0.3.5
